from weak_supervision.models.latent_alignment import LatentAlignment
from weak_supervision.models.latent_alignment_simple_decomposable_attention import LatentAlignmentDAM
from weak_supervision.models.latent_alignment_shared_char import LatentAlignmentSharedChar
from weak_supervision.models.latent_ibm_model_1 import LatentIbmModel1
from weak_supervision.models.semantic_parsing.wikitables_variable_free import (
        WikiTablesVariableFreeMml, WikiTablesVariableFreeErm)
